# Generated by Django 5.1.6 on 2025-02-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.TextField(help_text='Enter technologies separated by commas'),
        ),
    ]
