# Generated by Django 5.1.6 on 2025-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='project_images', to='main.projectimage'),
        ),
    ]
