# Generated by Django 5.1.6 on 2025-02-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/previews/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
    ]
