# Generated by Django 5.1.6 on 2026-04-21 13:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='preview_image',
            field=cloudinary.models.CloudinaryField(default='static/images/Screenshot_21.png', max_length=255, verbose_name='projects/previews/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/images/Screenshot_21.png', max_length=255, verbose_name='projects/images/'),
        ),
    ]
