# Generated by Django 5.1.6 on 2026-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_is_featured_alter_project_preview_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default="I'm Winner.", max_length=255)),
                ('hero_tagline', models.CharField(default='Software Engineer building and deploying SaaS products.', max_length=255)),
                ('typewriter_texts', models.JSONField(blank=True, default=list)),
                ('avatar_url', models.CharField(blank=True, default='/winners image.jpeg', max_length=500)),
                ('resume_url', models.CharField(blank=True, default='/WinnerOrluVictor_CV.pdf', max_length=500)),
                ('status_badge', models.CharField(blank=True, default='Available for hire', max_length=100)),
                ('about_quote', models.TextField(default="If it's complex, tedious, or critical, that's my lane.")),
                ('about_paragraphs', models.JSONField(blank=True, default=list)),
                ('about_tags', models.JSONField(blank=True, default=list)),
                ('skill_categories', models.JSONField(blank=True, default=list)),
                ('testimonials', models.JSONField(blank=True, default=list)),
                ('experiences', models.JSONField(blank=True, default=list)),
                ('contact_email', models.CharField(default='winnerbrown9@gmail.com', max_length=150)),
                ('contact_phone', models.CharField(default='+234 814 231 0497', max_length=50)),
                ('contact_location', models.CharField(default='Rivers State, Nigeria', max_length=150)),
                ('whatsapp_number', models.CharField(default='+2348142310497', max_length=50)),
                ('github_url', models.URLField(blank=True, default='https://github.com/winnerdebest')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/winner-orluvictor-944175333')),
                ('x_url', models.URLField(blank=True, default='https://x.com/buildwithwinner')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
